modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Arr"

[[mods]]
modId = "ifly"
version = "${version}"
displayName = "iFly"
authors = "Nanite"
description = '''
I believe I can fly
'''
#logoFile = ""

[[dependencies.ifly]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ifly]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"