modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "ifly"
version = "${version}"
displayName = "Ascension Shard"
authors = "Gaz"
description = '''
Adds a block that grants creative flight within its range **WORK IN PROGRESS**
'''
#logoFile = ""

[[dependencies.ifly]]
modId = "neoforge"
required = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ifly]]
modId = "minecraft"
required = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ifly]]
modId = "architectury"
required = true
versionRange = "[11.1.0,)"
ordering = "AFTER"
side = "BOTH"