modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "ifly"
version = "${version}"
displayName = "Ascension Shard"
authors = "Gaz"
description = '''
Adds a block that grants creative flight within its range **WORK IN PROGRESS**
'''
#logoFile = ""

[[dependencies.ifly]]
modId = "neoforge"
required = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ifly]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ifly]]
modId = "architectury"
required = true
versionRange = "[13.0.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ifly]]
modId = "resourcefullib"
required = true
versionRange = "[3.0.9,)"
ordering = "AFTER"
side = "BOTH"